---
- hosts: localhost
  remote_user: centos
  become_method: sudo
  become: true
  gather_facts: no
  tasks:
    - name: download java
      get_url:
        url: "http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.rpm"
        dest: /opt
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie; --no-check-certificate --no-cookies --header'

    - name: Copy rpm file to server
      copy:
        src: /opt/jdk-8u151-linux-x64.rpm
        dest: /tmp/jdk-8u151-linux-x64.rpm

    - name: Install java package
      yum: name=/opt/jdk-8u151-linux-x64.rpm state=present
      become: yes

    - name: Install packages
      yum: name={{ item }} state=present
      ignore_errors: yes
      with_items:
        - wget
        - epel-release
        - unzip
      become: true
            
    - name: Install initscripts
      yum: name=initscripts state=latest
      become: yes

    - name: setting env for java JBOSS
      shell: echo JAVA_HOME is $JAVA_HOME
      environment:
        JAVA_HOME: /usr/java/jdk1.8.0_151

    - shell: echo PATH is $PATH
      environment:
        PATH: $PATH:$JAVA_HOME/bin:.

    - shell: echo PATH is $PATH
      environment:
        CLASSPATH: $JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar:.

    - name: adding info to sonar file
      blockinfile:
        path: /etc/environment
        content: "\n export JAVA_HOME=$JAVA_HOME
                  \n export PATH=$PATH
                  \n export CLASSPATH=$CLASSPATH"

    - name: Download JBoss
      get_url: 
        url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.0.Final/jboss-as-7.1.0.Final.zip
        dest: /opt/jboss-as-7.1.0.Final.zip
        mode: 0755

    - name: Copy files of jboss
      copy: 
        src=/opt/jboss-as-7.1.0.Final 
        dest=/usr/share/jboss-as

    - name: Unarchive a file that needs to be downloaded
      unarchive:
        src: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.0.Final/jboss-as-7.1.0.Final.zip
        dest: /usr/share
        remote_src: yes
      become: true
   
    - name: Rename install directory
      command: chdir=/usr/share /bin/mv jboss-as-7.1.0.Final jboss-as creates=/usr/share/jboss-as
      notify: restart jboss

    - name: setting env for jboss home
      shell: echo JBOSS_HOME is $JBOSS_HOME
      environment:
        JBOSS_HOME: /usr/share/jboss-as/jboss-as-7.1.0.Final

    - shell: echo PATH is $PATH
      environment:
        PATH: $PATH:$JBOSS_HOME/bin:.

    - name: Add group "jboss"
      group: 
        name: jboss
  
    - name: Add user "jboss"
      user: 
        name: jboss 
        group: jboss 
        home: /usr/share/jboss-as
  
    - name: Change ownership of JBoss installation
      file: 
        path: /usr/share/jboss-as/ 
        owner: jboss 
        group: jboss 
        state: directory 
        recurse: yes
  
    - name: Copy the init script
      copy: 
        src: /usr/share/jboss-as/jboss-as-7.1.0.Final/bin/standalone.sh 
        dest: /etc/init.d/jboss 
        mode: 0755

    - name: daemon reload
      systemd:
        daemon_reload: yes
      become: true

    - name: start jboss service
      service:
        name: jboss
        state: started
        enabled: yes
      become: true

